name: 🔧 Image Optimization

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  optimize-images:
    name: Optimize Images
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout Repository
        uses: actions/checkout@v3

      - name: 📸 Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
